### ISSUE TITLE
Any way to test for a non-zero exit(status) condition?

### ISSUE THREAD

**Issue by bogen85** [mity/acutest#60]
First off, great test facility!

However, when testing error handling code to get full coverage sometimes exit is called with a non-zero status.
It would be nice if one could expect a specific exit status, similar to how one can expect a specific C++ exception to be thrown.

This is on Unix (Linux and FreeBSD) and forking is being done.

Is this something that you would accept a PR for? I'd only be able make it for Unix as I don't have access to any Windows development environment for stuff like this.

I'd also like to test for expected signals, in addition to expected non-zero status return.

For my own testing I'm applying this patch (which does not address those issues), and I'm not expecting to make PR for it:
```c
int acutest_check_(int cond, const char* file, int line, const char* fmt, ...);
 void acutest_case_(const char* fmt, ...);
@@ -1132,7 +1132,8 @@ acutest_run_(const struct acutest_test_* test, int index, int master_index)
             } else if(WIFSIGNALED(exit_code)) {
                 char tmp[32];
                 const char* signame;
-                switch(WTERMSIG(exit_code)) {
+                const int signum = WTERMSIG(exit_code);
+                switch(signum) {
                     case SIGINT:  signame = "SIGINT"; break;
                     case SIGHUP:  signame = "SIGHUP"; break;
                     case SIGQUIT: signame = "SIGQUIT"; break;
@@ -1141,9 +1142,10 @@ acutest_run_(const struct acutest_test_* test, int index, int master_index)
                     case SIGSEGV: signame = "SIGSEGV"; break;
                     case SIGILL:  signame = "SIGILL"; break;
                     case SIGTERM: signame = "SIGTERM"; break;
+                    case SIGFPE:  signame = "SIGFPE"; break;
                     default:      sprintf(tmp, "signal %d", WTERMSIG(exit_code)); signame = tmp; break;
                 }
-                acutest_error_("Test interrupted by %s.", signame);
+                acutest_error_("Test interrupted by %s (%d).", signame, signum);
             } else {
                 acutest_error_("Test ended in an unexpected way [%d].", exit_code);
             }
```

**Comment by bogen85** [comment]
I can always write mocks and check for expected non-zero status and for expected signals, but having acutest be able to check for these would be easier in some cases.

**Comment by mity** [comment]
In principle, it might be a nice feature. However I have two concerns:

1. It would likely be available for Unix-ish platforms only and I'm not sure whether offering some acutest's API for subset of supported platforms is the right thing to do. As pragmatic person as I am, I would say "yes, if the added value of the feature clearly exceeds the clutter".

2. But actually the added value is the 2nd concern I have. How the new API would look like? Would it in the end really simplify the usecase? My point is that if we just offer instead two macros `TEST_FORK()` and `TEST_WAIT()` wrapping the two respective syscalls, I don't see much value in it, you could just call `fork()` and `wait()` directly. (Or have two wrapper functions in your project, so that the return value gets tested via `TEST_CHECK` or something.) 

So as long as there is no concrete proposal for the new API making clear how it would made the use case easier, there is not much to discuss...

**Comment by bogen85** [comment]
Thanks.

>  I don't see much value in it, you could just call `fork()` and `wait()` directly. (Or have two wrapper functions in your project, so that the return value gets tested via `TEST_CHECK` or something.)

Actually this may be better solution. 

I've been using pytest a lot and it has a `with pytest.raises(Exception) as e_info:` mechanism which can be use to check exit conditions.

I'm already wrapping acutest to some degree (though acutest still only gets included once) so adding the extra `TEST_CHECK` or something would not be a big deal.
