### ISSUE TITLE
CUTest tutorial available

### ISSUE THREAD

**Issue by tomcam** [mity/acutest#8]
Don't know if you're interested, but I wrote a tutorial on CUTest at (https://github.com/tomcam/mity-cutest/blob/master/README.md). Happy to make any changes/additions to it, submit as PR, whatever.

**Comment by mity** [comment]
That's great.

It might be good to add it directly into the cutest repo, if it is adapted a little bit (e.g. to make relative/local references to `cutest.h`).

Just few minor things I noticed:

Some code lines in the examples differ, likely unintentionally. E.g.:
~~~
    { "PI accurate to 7 digits", pi_accurate_to_7_digits },
~~~
vs.
~~~
    { "PI accurate to 7 digits?", pi_accurate_to_7_digits },
~~~
(See the question mark).

Another example:
~~~
    TEST_CHECK(PI == 3.1415927);
~~~
vs.
~~~
    TEST_CHECK(PI == 3.1415927f);
~~~
(See the `f` suffix).

Also I am unsure if tutorial should promote unit test names with spaces: When specifying such unit test name on command line then requires escaping or quotes.

Last but not least, the implementation of `pi_accurate_to_7_digits()` is somewhat problematic and fragile: It does not work if `PI` is defined with better precision then the 7 digits. So it should either do some rounding of `PI` to the expected precision, or it should check that `PI` is in the range `[3.1415927f - 0.,5e-7; 3.1415927f + 0.5e-7)` instead of equality.

**Comment by irontribe** [comment]
Thanks kindly! I'll fix all that stuff. One problem--I don't know which unit test names had spaces? I absolutely didn't want that to happen but can't find it anywhere.

**Comment by mity** [comment]
"PI accurate to 7 digits"

**Comment by mity** [comment]
Closing as I cannot see any progress.

If you eventually do it, feel free to ping me or reopen this. (Ideal would be creating pull request for it.)
